<a href="https://colab.research.google.com/github/laxitdange28-tech/Pandas-notes/blob/main/Pandas_Class1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 1: Introduction & Setup
Welcome to your first class on **Pandas**. In this session, we'll learn what Pandas is, why we use it, and how to get started with Series and DataFrames.

## 1 What is Pandas and Why Use It?
Pandas is a powerful **Python library** for data analysis and manipulation.

Key points:
- Provides two main data structures: **Series** (1D) and **DataFrame** (2D).
- Makes working with tabular data easy and fast.
- Ideal for cleaning, transforming, and analyzing datasets.
- Works well with other libraries like NumPy, Matplotlib, and Scikit-Learn.

## 2 Installing & Importing Pandas
To install pandas, open your terminal or command prompt and run:
```bash
pip install pandas
```
Then, you can import it in Python as follows:

In [ ]:
import pandas as pd

## 3 Understanding Series & DataFrame
- **Series**: One-dimensional labeled array, like a column in Excel.
- **DataFrame**: Two-dimensional table, similar to an Excel sheet or SQL table.

### Creating a Series from Python Lists or Dictionaries

In [ ]:
import pandas as pd
marks = pd.Series([10,20,30,40,50],index=['Ronaldo','Messi','Virat','Dhoni','Mbappe'])

print(marks['Virat'])

30


### Creating a DataFrame

In [ ]:
df = pd.DataFrame({
    'Name':['Ronaldo','Messi','Virat','Dhoni','Mbappe'],
    'Age':[35,34,33,32,31],
    'marks':[10,20,30,40,50]
    })
print(df)

# Selecting a column
print(df['Age'])

# To get specific row we use .loc
print(df.loc[0])

# select a specific value
print(df.loc[1,'Name'])

      Name  Age  marks
0  Ronaldo   35     10
1    Messi   34     20
2    Virat   33     30
3    Dhoni   32     40
4   Mbappe   31     50
0    35
1    34
2    33
3    32
4    31
Name: Age, dtype: int64
Name     Ronaldo
Age           35
marks         10
Name: 0, dtype: object
Messi


### Creating DataFrame from NumPy Arrays

In [ ]:
information = pd.DataFrame([
    ['Rahul',52,80],
    ['Devraj',22,85],
    ['Rohit',60,55]

], columns=['Name','Age','Marks']
    )
print(information)

print(information.loc[1,'Marks'])

# To get specific row we use .loc
print(information.loc[1])

     Name  Age  Marks
0   Rahul   52     80
1  Devraj   22     85
2   Rohit   60     55
85
Name     Devraj
Age          22
Marks        85
Name: 1, dtype: object


In [ ]:
# generete a 3x4 materix with random numbers(1-13) using numpy
# name the columns as [a,b,c,d]
import numpy as np
matrix = np.random.randint(1,13, size=(3,4))
print(matrix)
df = pd.DataFrame(matrix,columns=['A','B','C','D'])
print(df)

[[ 9  6 11  1]
 [ 4  2  7  8]
 [ 2 11  8  5]]
   A   B   C  D
0  9   6  11  1
1  4   2   7  8
2  2  11   8  5


### Reading CSV / Excel Files (Sneak Peek)
You can read external data using:
```python
pd.read_csv('file.csv')
```
```python
pd.read_excel('file.xlsx')
```
We will explore this in detail later.

---
**Summary**
- Pandas is a must-know library for data analysis.
- We learned about Series & DataFrames.
- We saw how to create them from lists, dictionaries, NumPy arrays, and got a sneak peek at CSV/Excel files.